"""
Constants package
Centralized constants for the application
"""

# Error Messages
from .error_messages import (
    ACCOUNT_DEACTIVATED,
    CURRENT_PASSWORD_INCORRECT,
    DATABASE_ERROR,
    EMAIL_ALREADY_EXISTS,
    INTERNAL_ERROR,
    INVALID_CREDENTIALS,
    INVALID_EMAIL_FORMAT,
    INVALID_INPUT_FORMAT,
    INVALID_PASSWORD,
    INVALID_TOKEN_TYPE,
    PASSWORD_MISMATCH,
    PASSWORD_TOO_WEAK,
    REQUIRED_FIELD_MISSING,
)
from .error_messages import SERVICE_UNAVAILABLE as SERVICE_UNAVAILABLE_MSG
from .error_messages import (
    TOKEN_EXPIRED,
    TOKEN_REVOKED,
    UNAUTHORIZED_ACCESS,
    USER_INACTIVE,
    USER_NOT_FOUND,
    VALIDATION_FAILED,
)

# HTTP Status Codes
from .http_status import (
    ACCEPTED,
    BAD_GATEWAY,
    BAD_REQUEST,
    CONFLICT,
    CREATED,
    FORBIDDEN,
    GATEWAY_TIMEOUT,
    INTERNAL_SERVER_ERROR,
    METHOD_NOT_ALLOWED,
    NO_CONTENT,
    NOT_FOUND,
    NOT_IMPLEMENTED,
    OK,
    SERVICE_UNAVAILABLE,
    TOO_MANY_REQUESTS,
    UNAUTHORIZED,
    UNPROCESSABLE_ENTITY,
)

# Token Constants
from .token_constants import (
    ACCESS_TOKEN_TYPE,
    EXPIRY_CLAIM,
    JTI_CLAIM,
    LOGOUT_ALL_REASON,
    LOGOUT_REASON,
    MANUAL_REVOKE_REASON,
    PASSWORD_CHANGE_REASON,
    REFRESH_TOKEN_TYPE,
    SUBJECT_CLAIM,
    TOKEN_ROTATION_REASON,
    TOKEN_TYPE_CLAIM,
)

__all__ = [
    # Token Constants
    "ACCESS_TOKEN_TYPE",
    "REFRESH_TOKEN_TYPE",
    "LOGOUT_REASON",
    "TOKEN_ROTATION_REASON",
    "PASSWORD_CHANGE_REASON",
    "MANUAL_REVOKE_REASON",
    "LOGOUT_ALL_REASON",
    "TOKEN_TYPE_CLAIM",
    "JTI_CLAIM",
    "SUBJECT_CLAIM",
    "EXPIRY_CLAIM",
    # HTTP Status Codes
    "OK",
    "CREATED",
    "ACCEPTED",
    "NO_CONTENT",
    "BAD_REQUEST",
    "UNAUTHORIZED",
    "FORBIDDEN",
    "NOT_FOUND",
    "METHOD_NOT_ALLOWED",
    "CONFLICT",
    "UNPROCESSABLE_ENTITY",
    "TOO_MANY_REQUESTS",
    "INTERNAL_SERVER_ERROR",
    "NOT_IMPLEMENTED",
    "BAD_GATEWAY",
    "SERVICE_UNAVAILABLE",
    "GATEWAY_TIMEOUT",
    # Error Messages
    "INVALID_CREDENTIALS",
    "ACCOUNT_DEACTIVATED",
    "UNAUTHORIZED_ACCESS",
    "INVALID_TOKEN_TYPE",
    "TOKEN_EXPIRED",
    "TOKEN_REVOKED",
    "USER_NOT_FOUND",
    "USER_INACTIVE",
    "EMAIL_ALREADY_EXISTS",
    "INVALID_EMAIL_FORMAT",
    "INVALID_PASSWORD",
    "PASSWORD_TOO_WEAK",
    "CURRENT_PASSWORD_INCORRECT",
    "PASSWORD_MISMATCH",
    "VALIDATION_FAILED",
    "REQUIRED_FIELD_MISSING",
    "INVALID_INPUT_FORMAT",
    "INTERNAL_ERROR",
    "DATABASE_ERROR",
    "SERVICE_UNAVAILABLE_MSG",
]
