import os

from dotenv import load_dotenv

load_dotenv()

ACCESS_TOKEN_EXPIRES = 3600
REFRESH_TOKEN_EXPIRES = 2592000
ALGORITHM = "HS256"
ERROR_MESSAGE_KEY = "message"
HEADER_NAME = "Authorization"
SECRET_KEY = os.getenv("SECRET_KEY", "me_may_beo")


class JWTConfig:
    JWT_SECRET_KEY = SECRET_KEY
    JWT_ACCESS_TOKEN_EXPIRES = ACCESS_TOKEN_EXPIRES  # 1 hour in seconds
    JWT_REFRESH_TOKEN_EXPIRES = REFRESH_TOKEN_EXPIRES  # 30 days in seconds
    JWT_ALGORITHM = ALGORITHM

    JWT_TOKEN_LOCATION = ["headers", "cookies"]
    JWT_HEADER_NAME = HEADER_NAME
    JWT_HEADER_TYPE = "Bearer"

    JWT_ERROR_MESSAGE_KEY = ERROR_MESSAGE_KEY
